"""Initial migration

Revision ID: 2a547488aaa8
Revises: 
Create Date: 2024-07-29 11:04:53.019195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a547488aaa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###


def upgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###

