"""Add CustomerDetails

Revision ID: 8f14d7110c6d
Revises: 4f186330e7cc
Create Date: 2024-10-22 19:55:41.693070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f14d7110c6d'
down_revision = '4f186330e7cc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_details',
    sa.Column('customer_detail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_detail_id')
    )
    with op.batch_alter_table('customer_details', schema=None) as batch_op:
        batch_op.create_index('ix_company_name', ['company_name'], unique=False)
        batch_op.create_index('ix_customer_details_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_details', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_details_user_id')
        batch_op.drop_index('ix_company_name')

    op.drop_table('customer_details')
    # ### end Alembic commands ###


def upgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

