"""Add products table

Revision ID: 933078c513e2
Revises: 7b34ea9e98e1
Create Date: 2025-04-16 19:10:50.935290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933078c513e2'
down_revision = '7b34ea9e98e1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.drop_table('products')
    # ### end Alembic commands ###


def upgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

