"""Initial migration

Revision ID: c1c94f4d4b42
Revises: 
Create Date: 2024-07-27 18:39:54.417196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c94f4d4b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('reports')
    op.drop_table('audit_logs')
    op.drop_table('order_details')
    op.drop_table('payments')
    op.drop_table('roles')
    op.drop_table('driver_details')
    op.drop_table('warehouses')
    op.drop_table('orders')
    op.drop_table('user_details')
    op.drop_table('users')
    op.drop_table('shipments')
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_plate', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fuel_capacity', sa.FLOAT(), nullable=False),
    sa.Column('litres_per_100jkm', sa.FLOAT(), nullable=False),
    sa.Column('tonnage', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_plate')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=255), nullable=False),
    sa.Column('departure_time', sa.DATETIME(), nullable=True),
    sa.Column('arrival_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_details',
    sa.Column('user_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_detail_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('order_uuid', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_uuid')
    )
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.INTEGER(), nullable=False),
    sa.Column('warehouse_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=False),
    sa.Column('docks', sa.INTEGER(), nullable=False),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_table('driver_details',
    sa.Column('driver_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('license_expiry', sa.DATETIME(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_status', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('driver_detail_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('order_details',
    sa.Column('order_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('generated_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('data', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    # ### end Alembic commands ###


def upgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('orders_placed')
    # ### end Alembic commands ###


def downgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_placed',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('order_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=False),
    sa.Column('total_weight', sa.FLOAT(), nullable=False),
    sa.Column('total_volume', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_uuid')
    )
    op.create_table('order_products',
    sa.Column('order_product_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders_placed.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_product_id')
    )
    # ### end Alembic commands ###

