"""Delete test models

Revision ID: f31aa6e4debe
Revises: 2a547488aaa8
Create Date: 2024-07-29 11:05:35.728523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31aa6e4debe'
down_revision = '2a547488aaa8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def upgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###


def downgrade_wms():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('test_id', sa.INTEGER(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###

